GET http://localhost:3001/api/notes/

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS code rest client is a pretty handy tool",
    "important": true
}

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
